# Generated by Django 5.2 on 2025-04-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='genero',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
