# Generated by Django 5.2 on 2025-04-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_libro_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
